### ISSUE TITLE
cmf_curl_get 函数不存在

### ISSUE THREAD

**Issue by fjnphsq** [thinkcmf/thinkcmfapi#1]
调用/wxapp/public/login 时返回500错误，提示的是cmf_curl_get不存在

我在wxapp下添加了common.php添加了该函数，如下：

**Comment by thinkcmf** [comment]
@fjnphsq 已经修复，请下载最新的 cmf5核心包

**Comment by thinkcmf** [comment]
@fjnphsq 已经修复，请测试
