### ISSUE TITLE
API版图片路径问题

### ISSUE THREAD

**Issue by chaoLR** [thinkcmf/thinkcmfapi#4]
> /**
> 
>  * 获取图片预览链接
>  * @param string $file 文件路径，相对于upload
>  * @param string $style 图片样式,支持各大云存储
>  * @return string
>  */
> function cmf_get_image_preview_url($file, $style = 'watermark')
> {
>     if (strpos($file, "http") === 0) {
>         return $file;
>     } else if (strpos($file, "/") === 0) {
>         return $file;
>     } else {
>         $storage = Storage::instance();
>         return $storage->getPreviewUrl($file, $style);
>     }
> }

图片预览链接方法不适合api版
后台生成图片路径不在public\api\upload,所以会出现找不到图片

**Comment by wurining** [comment]
我也遇到了这个问题
