### ISSUE TITLE
请问这个在nginx下要怎么配置rewrite规则

### ISSUE THREAD

**Issue by xinchuangfu** [thinkcmf/thinkcmfapi#6]
http://apixcx.xxxx.com/api/redline/My/userinfo 访问这个的时候提示api模块不存在

**Comment by wurining** [comment]
前缀 http://apixcx.xxxx.com/api/
模块 redline
控制器 My
方法 userinfo
使用api模块时我对Nginx规则进行了重写，否则会出现这种情况。
